### PR TITLE
Statebag Attempt?

### PR DESCRIPTION
**Pull request by googleoblivion**
Needs testing with multiple people, I don't have friends.

### CODE REVIEW

**Comment by Randolio** [comment]
Don't think this is gonna work with multiple people around. From experience with a tow script, you'd need control of both entities and even still, I ran into issues where it would be attached for me but not for the person next to me, or vice versa.

**Comment by googleoblivion** [comment]
Idk don't have test capacity, i guess the crate could be spawned and attached within the statebag.

**Comment by Randolio** [comment]
i did attempt this myself using a non networked crate object replicated to everyone but if you went out of scope and came back in, the prop would duplicate and damage the vehicle. My knowledge of statebags isn't too great unfortunately.

**Comment by googleoblivion** [comment]
What about https://docs.fivem.net/natives/?_0x9F7F8D36 set on the crate during spawn, would the original statebag then allow attachments?

**Comment by googleoblivion** [comment]
image
I have it attaching to the truck, i might try to do the multiple client thing to test 👍

**Comment by googleoblivion** [comment]
image
image

I would assume this is leaving scope enough.
image
image

**Comment by Randolio** [comment]
IMG_1998

**Pull request closed without merging**
